### ISSUE TITLE
Errors that should be warnings.

### ISSUE THREAD

**Issue by Matthew-Wilkinson** [MBravoS/splotch#45]
In pyplot, empty hist2d makes a blank graph.
`
In [14]: plt.hist2d([],[]) `
`
Out[14]: 
(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 <matplotlib.collections.QuadMesh at 0x7f817cfa3210>)
`

In splotch, empty hist2D gives an error.
`
splt.hist2D([],[])`
`
Traceback (most recent call last):
  File "<ipython-input-16-ab27224e5252>", line 1, in <module>
    splt.hist2D([],[])
  File "/home/matt/anaconda3/lib/python3.7/site-packages/splotch/plots_2d.py", line 614, in hist2D
    X,Y,Z=basehist2D(x,y,c,bin_type,bins,scale,dens,cstat,xlog,ylog)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/splotch/base_func.py", line 73, in basehist2D
    x_temp,x_bins_hist,x_bins_plot=bin_axis(x,bin_type[0],bin_num[0],log=xlog)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/splotch/base_func.py", line 159, in bin_axis
    hist_bins=bfunc[btype](data,bins)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/splotch/base_func.py", line 117, in N
    if nanmin(d)==nanmax(d):
  File "<__array_function__ internals>", line 6, in nanmin
  File "/home/matt/anaconda3/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 328, in nanmin
    res = np.amin(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 6, in amin
  File "/home/matt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
`

**Comment by AstroRobin** [comment]
Okay thanks for pointing this out, this looks like it's embedded deep down in our base histogram function. I'll have a look into it, should be an easy fix.

**Comment by MBravoS** [comment]
Fixed in version 0.4.6.7
